spring.application.name=australiantoiletfinder

spring.jpa.defer-datasource-initialization = true

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.security.user.name=guest
spring.security.user.password=pulsar

logging.level.org.springframework=debug
logging.level.com.reedmanit.australiantoiletfinder=debug
spring.mvc.format.date=yyyy-MM-dd

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

## PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/AustralianToilets
spring.datasource.username=app
spring.datasource.password=pulsar
spring.jpa.show-sql=true

# seems to get around login problem re sw.js
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

# Error handling configuration
server.error.path=/error  # Specifies the default error path
server.error.whitelabel.enabled=false