spring.application.name=australiantoiletfinder

spring.jpa.defer-datasource-initialization = true

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.security.user.name=${PROD_USER}
spring.security.user.password=${PROD_PASSWORD}

logging.level.org.springframework=info
logging.level.com.reedmanit.australiantoiletfinder=info
spring.mvc.format.date=yyyy-MM-dd

logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO

## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://${PROD_DB_HOST}:5432/${PROD_DB_NAME}
spring.datasource.username=${PROD_DB_USER}
spring.datasource.password=${PROD_DB_PASSWORD}

# seems to get around login problem re sw.js
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

# Error handling configuration
server.error.path=/error  # Specifies the default error path
server.error.whitelabel.enabled=false